name: Wikipedia Welcome Bot

on:
  schedule:
    - cron: '*/1 * * * *'  # hər dəqiqə işə düşür
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Python quraşdır
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Lazım olan paketləri quraşdır
        run: pip install requests
      - name: Boti işə sal
        run: python welcome_bot.py
