name: Wikipedia Welcome Bot

on:
  schedule:
    - cron: '*/10 * * * *'  # hər 10 dəqiqədə bir işə düşəcək
  workflow_dispatch:        # manual run üçün də imkan qalacaq

jobs:
  welcome:
    runs-on: ubuntu-latest
    steps:
      - name: Kodları checkout et
        uses: actions/checkout@v4

      - name: Python quraşdır
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Asılılıqları quraşdır
        run: |
          pip install -r requirements.txt

      - name: Botu işə sal
        run: |
          python bot.py
